### ISSUE TITLE
Doc header icons off on some pages

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#45]
Doc header icons are supposed to look good, like this:

![image](https://github.com/temperlang/temper/assets/27425/50879b0b-3082-48b9-be63-09df76ed462c)

But on some reference pages, they look bad, like this:

![image](https://github.com/temperlang/temper/assets/27425/f94a017d-115b-4aec-ae5d-e605a1156137)

These are the pages I've seen with this problem:

- [Types and Values](https://temperlang.github.io/tld/reference/types/)
- [Builtin Functions and Constants](https://temperlang.github.io/tld/reference/builtins/)
- [Syntax Reference](https://temperlang.github.io/tld/reference/syntax/)

**Comment by tjpalmer** [comment]
If the types.md content is just this, it still breaks:

```md
![BooleanLiteral &#58;&#61; &#34;false&#34; &#124; &#34;true&#34;](../snippet/syntax/BooleanLiteral/snippet.svg)
```

But if I take that out, it's good, so presumably it's something in the svg that's breaking.

**Comment by tjpalmer** [comment]
And specifically, it's these style rules that break things:

```css
	svg {
		background-color: hsl(30,20%,95%);
	}
	path {
		stroke-width: 3;
		stroke: black;
		fill: rgba(0,0,0,0);
	}
```

This one is probably also risky:

```css
	text {
		font: bold 14px monospace;
		text-anchor: middle;
		white-space: pre;
	}
```
